trigger:
- main

variables:
  - name: adminPassword
    value: $(TF_VAR_admin_password)

pool:
  name: 'Anshuman_agent'

stages:
- stage: PrepareAndPlan
  displayName: 'Prepare & Plan Terraform'
  jobs:
  - job: Plan
    displayName: 'Terraform Plan'
    steps:
    
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.8.5'

    - task: AzureCLI@2
      displayName: 'Azure Login (Implicit)'
      inputs:
        azureSubscription: 'Anshuman_final'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure credentials sourced successfully."

    - task: CmdLine@2
      displayName: 'Terraform Init'
      inputs:
        script: |
          terraform init -upgrade
        workingDirectory: 'anshumanmishramidsemtask/environments/dev'

    - task: CmdLine@2
      displayName: 'Terraform Validate'
      inputs:
        script: |
          terraform validate
        workingDirectory: 'anshumanmishramidsemtask/environments/dev'

    - task: CmdLine@2
      displayName: 'Terraform Plan'
      inputs:
        script: |
          terraform plan -var="vm_admin_password=$(adminPassword)" -out=tfplan
        workingDirectory: 'anshumanmishramidsemtask/environments/dev'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Terraform Plan'
      inputs:
        targetPath: 'anshumanmishramidsemtask/environments/dev/tfplan'
        artifact: 'tfplan'
        publishLocation: 'pipeline'

- stage: DeploymentApproval
  displayName: 'Manual Review'
  jobs:
  - deployment: Review
    displayName: 'Deployment Approval'
    environment: 'ProdEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Plan complete. Awaiting manual approval to apply changes."
              displayName: 'Awaiting Approval'

- stage: ApplyDeployment
  displayName: 'Apply Terraform Changes'
  dependsOn: DeploymentApproval
  condition: succeeded()

  jobs:
  - job: Apply
    displayName: 'Terraform Apply'
    steps:
    
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Terraform Plan'
      inputs:
        buildType: 'current'
        artifactName: 'tfplan'
        targetPath: '$(Pipeline.Workspace)/tfplan'
        
    - task: AzureCLI@2
      displayName: 'Azure Re-Login'
      inputs:
        azureSubscription: 'Anshuman_final'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure re-authenticated."
          
    - task: TerraformInstaller@1
      displayName: 'Ensure Terraform is Installed'
      inputs:
        terraformVersion: '1.8.5'

    - task: CmdLine@2
      displayName: 'Terraform Apply'
      inputs:
        script: |
          terraform apply -auto-approve $(Pipeline.Workspace)/tfplan/tfplan
        workingDirectory: 'anshumanmishramidsemtask/environments/dev'

    - task: CmdLine@2
      displayName: 'Output Deployment Details'
      inputs:
        script: |
          terraform output -json > output.json
          cat output.json
        workingDirectory: 'anshumanmishramidsemtask/environments/dev'