pipeline {
    agent {
        docker { image 'mcr.microsoft.com/azure-cli' }
    }

    environment {
        AZURE_CREDENTIALS = credentials('AZURE_CREDENTIALS')
        TF_VAR_vm_admin_password = credentials('TF_VAR_vm_admin_password')
    }

    stages {

        stage('Azure Login') {
            steps {
                script {
                    def creds = readJSON text: AZURE_CREDENTIALS
                    sh """
                    az login --service-principal \
                        -u ${creds.clientId} \
                        -p ${creds.clientSecret} \
                        --tenant ${creds.tenantId}
                    az account set --subscription ${creds.subscriptionId}
                    """
                }
            }
        }

        stage('Install Terraform') {
            steps {
                sh '''
                apk add --no-cache wget unzip
                wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
                unzip terraform_1.5.7_linux_amd64.zip
                mv terraform /usr/local/bin/
                terraform --version
                '''
            }
        }

        stage('Terraform Init and Plan') {
            steps {
                dir('anshumanmishramidsemtask/environments/dev') {
                    sh 'terraform init -upgrade'
                    sh 'terraform plan -var="vm_admin_password=$TF_VAR_vm_admin_password" -out=tfplan'
                }
            }
        }

        stage('Terraform Apply') {
            when {
                expression { return params.APPLY_CHANGES == true }
            }
            steps {
                dir('anshumanmishramidsemtask/environments/dev') {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }

    parameters {
        booleanParam(name: 'APPLY_CHANGES', defaultValue: false, description: 'Apply Terraform changes automatically')
    }

    post {
        always {
            cleanWs()
        }
    }
}
